### ISSUE TITLE
opendac dataset

### ISSUE THREAD

**Issue by HarshaSatyavardhan** [Open-Catalyst-Project/odac-data#3]
As I can see in this repository there are only 242 mof's(pristine+defects) present where in the paper its mentioned 8412 mof's(pristine_defects)

**Comment by anuroopsriram** [comment]
Hi: These 242 MOFs are the promising ones (as defined in our paper). The full dataset is in: https://github.com/Open-Catalyst-Project/ocp/blob/main/DATASET.md#open-direct-air-capture-2023-odac23
